[workspace]
resolver = "2"
members = [
    "drydoc",
    "drydoc_usage",
]

[workspace.package]
version = "1.0.1"
rust-version = "1.82"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/schneems/drydoc"
documentation = "https://docs.rs/drydoc"
